"""
Database Models Package

Contains all Pydantic and SQLAlchemy models for the Gator AI platform.
"""

from .acd import (  # Scheduling enums
    ACDContextCreate,
    ACDContextModel,
    ACDContextResponse,
    ACDContextUpdate,
    ACDStats,
    ACDTraceArtifactCreate,
    ACDTraceArtifactModel,
    ACDTraceArtifactResponse,
    ACDValidationReport,
    AIComplexity,
    AIConfidence,
    AIQueuePriority,
    AIQueueStatus,
    AIRequest,
    AIState,
    AIStatus,
    AIValidation,
    HandoffStatus,
    HandoffType,
    ScheduleDecisionSource,
    ScheduleFeedbackType,
    ScheduleOptimizationGoal,
    ScheduleType,
    SkillLevel,
)

# Business Intelligence models
from .business_intelligence import (
    ChurnRiskLevel,
    ContentScheduleCreate,
    ContentScheduleModel,
    ContentScheduleResponse,
    RevenueInsightModel,
    RevenueInsightResponse,
    RevenuePeriod,
    SchedulingFeedbackModel,
    SchedulingFeedbackResponse,
    TrafficMetricsModel,
    TrafficMetricsResponse,
    TrafficSource,
    UserRetentionModel,
    UserRetentionResponse,
)
from .content import (
    ContentCreate,
    ContentListResponse,
    ContentModel,
    ContentRating,
    ContentResponse,
    ContentStats,
    ContentType,
    ContentUpdate,
    GenerationRequest,
    ModerationStatus,
)
from .conversation import ConversationCreate, ConversationModel, ConversationResponse
from .feed import (
    FeedItemListResponse,
    FeedItemModel,
    FeedItemResponse,
    RSSFeedCreate,
    RSSFeedModel,
    RSSFeedResponse,
    RSSFeedUpdate,
)
from .generation_feedback import (
    BenchmarkStats,
    FeedbackRating,
    FeedbackSubmission,
    GenerationBenchmarkCreate,
    GenerationBenchmarkModel,
    GenerationBenchmarkResponse,
)

# Installed Model models
from .installed_model import (
    InstalledModelCreate,
    InstalledModelModel,
    InstalledModelResponse,
    InstalledModelUpdate,
    ModelsByTriggerResponse,
    ModelSource,
    ModelType,
    TriggerWordResponse,
)
from .message import MessageCreate, MessageModel, MessageResponse
from .persona import PersonaCreate, PersonaModel, PersonaResponse, PersonaUpdate
from .ppv_offer import PPVOfferCreate, PPVOfferModel, PPVOfferResponse
from .user import UserCreate, UserModel, UserResponse, UserUpdate

__all__ = [
    "PersonaModel",
    "PersonaCreate",
    "PersonaResponse",
    "PersonaUpdate",
    "UserModel",
    "UserCreate",
    "UserResponse",
    "UserUpdate",
    "ConversationModel",
    "ConversationCreate",
    "ConversationResponse",
    "MessageModel",
    "MessageCreate",
    "MessageResponse",
    "PPVOfferModel",
    "PPVOfferCreate",
    "PPVOfferResponse",
    # Content models
    "ContentModel",
    "ContentCreate",
    "ContentResponse",
    "ContentUpdate",
    "GenerationRequest",
    "ContentListResponse",
    "ContentStats",
    "ContentType",
    "ContentRating",
    "ModerationStatus",
    # Feed models
    "RSSFeedModel",
    "FeedItemModel",
    "RSSFeedCreate",
    "RSSFeedResponse",
    "RSSFeedUpdate",
    "FeedItemResponse",
    "FeedItemListResponse",
    # Generation feedback models
    "GenerationBenchmarkModel",
    "GenerationBenchmarkCreate",
    "GenerationBenchmarkResponse",
    "FeedbackSubmission",
    "FeedbackRating",
    "BenchmarkStats",
    # ACD models
    "ACDContextModel",
    "ACDTraceArtifactModel",
    "ACDContextCreate",
    "ACDContextUpdate",
    "ACDContextResponse",
    "ACDTraceArtifactCreate",
    "ACDTraceArtifactResponse",
    "ACDValidationReport",
    "ACDStats",
    "AIStatus",
    "AIComplexity",
    "AIConfidence",
    "AIRequest",
    "AIState",
    "AIQueuePriority",
    "AIQueueStatus",
    "AIValidation",
    "HandoffType",
    "HandoffStatus",
    "SkillLevel",
    # Scheduling enums
    "ScheduleType",
    "ScheduleOptimizationGoal",
    "ScheduleDecisionSource",
    "ScheduleFeedbackType",
    # Business Intelligence models
    "TrafficMetricsModel",
    "UserRetentionModel",
    "RevenueInsightModel",
    "ContentScheduleModel",
    "SchedulingFeedbackModel",
    "TrafficSource",
    "ChurnRiskLevel",
    "RevenuePeriod",
    "TrafficMetricsResponse",
    "UserRetentionResponse",
    "RevenueInsightResponse",
    "ContentScheduleCreate",
    "ContentScheduleResponse",
    "SchedulingFeedbackResponse",
    # Installed Model models
    "InstalledModelModel",
    "InstalledModelCreate",
    "InstalledModelUpdate",
    "InstalledModelResponse",
    "TriggerWordResponse",
    "ModelsByTriggerResponse",
    "ModelType",
    "ModelSource",
]
